services:
  sandbox-template:
    build:
      context: . # Path to the directory containing your Dockerfile
      dockerfile: e2b.Dockerfile # Name of your Dockerfile (if it's named differently)
    image: sandbox-template:latest
    container_name: sandbox-template
    ports:
      - "4983:4983" # Additional port
      - "8080:8080" # VS Code server

    command: tail -f /dev/null
    stdin_open: true
    tty: true
